name: Trigger on PR Merge with Comment

on:
  pull_request:
    types:
      - closed

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was merged with comment
        id: check-comment
        run: |
          pr_number=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
          merge_comment=false
          issue_tags=""
          comments=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${pr_number}/comments")

          for comment in $(echo "$comments" | jq -r '.[].body'); do
          if [[ "$comment" =~ fixes\ #[0-9]+ ]]; then
            merge_comment=true
            issue_number=$(echo "$comment" | grep -o -E 'fixes #[0-9]+' | grep -o -E '[0-9]+')
            issue_tags=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${issue_number}/labels" | jq -r '.[].name')
            break  # Exit the loop once a relevant comment is found
          fi
          done
          echo "::set-output name=merge_comment::$merge_comment"
          echo "::set-output name=issue_tags::$issue_tags"
        shell: bash

      - name: Send POST request
        if: steps.check-comment.outputs.merge_comment == 'true'
        env:
          GITHUB_USERNAME: ${{ github.event.pull_request.user.login }}
          GITHUB_COMMENT: ${{ steps.check-comment.outputs.comment }}
          ISSUE_TAGS: ${{ steps.check-comment.outputs.issue_tags }}
          AUTHORIZATION_HEADER: ${{ secrets.TOKEN }}
        run: |
          url=${{ secrets.URL }}
          payload="{\"username\":\"$GITHUB_USERNAME\",\"comment\":\"$GITHUB_COMMENT\",\"issue_tags\":\"$ISSUE_TAGS\"}"
          curl -X POST -H "Authorization: $AUTHORIZATION_HEADER" -H "Content-Type: application/json" -d "$payload" "$url"
